name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      title:
        description: 'Release title'
        required: true
        type: string
      notes:
        description: 'Release notes'
        required: false
        type: string

jobs:
  build-all-platforms:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x64
            ext: tar.gz
          - os: windows-latest
            platform: windows-x64
            ext: zip
          - os: macos-latest
            platform: macos-arm64
            ext: tar.gz
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install LLVM (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-14-dev clang-14 cmake build-essential libffi-dev
    
    - name: Install LLVM (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install llvm cmake
    
    - name: Install LLVM (Windows)
      if: runner.os == 'Windows'
      run: choco install llvm cmake
    
    - name: Build (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        chmod +x build.sh
        ./build.sh
    
    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: .\build.bat
    
    - name: Package (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        mkdir -p dist
        cp -r build/bin dist/xypher-${{ matrix.platform }}
        cp README.md LICENSE NOTICE dist/xypher-${{ matrix.platform }}/
        tar czf xypher-${{ matrix.platform }}.${{ matrix.ext }} -C dist xypher-${{ matrix.platform }}
    
    - name: Package (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir dist
        xcopy /E /I build\bin dist\xypher-${{ matrix.platform }}
        copy README.md dist\xypher-${{ matrix.platform }}\
        copy LICENSE dist\xypher-${{ matrix.platform }}\
        copy NOTICE dist\xypher-${{ matrix.platform }}\
        Compress-Archive -Path dist\xypher-${{ matrix.platform }} -DestinationPath xypher-${{ matrix.platform }}.${{ matrix.ext }}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: xypher-${{ matrix.platform }}
        path: xypher-${{ matrix.platform }}.${{ matrix.ext }}
  
  create-release:
    needs: build-all-platforms
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.title }}
        body: ${{ github.event.inputs.notes }}
        draft: false
        prerelease: false
        files: |
          artifacts/xypher-linux-x64/*.tar.gz
          artifacts/xypher-windows-x64/*.zip
          artifacts/xypher-macos-arm64/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

